### PR TITLE
Enable Symfony3

### PR DESCRIPTION
**Pull request by norfil**

### CODE REVIEW

**Comment by SimonSimCity** [comment]
@norfil Thanks for the update. My project hasn't received the update yet, but will soon.

**Comment by norfil** [comment]
Thank you for your time ! Could you please tag a new minor release to make this merge easily usable through composer on Symfony 3 projects ?

**Comment by SimonSimCity** [comment]
@norfil done. The version 2.1.0 now officially supports Symfony 3 :smiley:

**Comment by norfil** [comment]
Good job !

**Pull request merged**
